#! /bin/sh

xrandr --output VGA-1 --off --output HDMI-1 --off --output DP-1 --primary --mode 3840x1600 --pos 3840x560 --rotate normal --output HDMI-2 --off --output HDMI-3 --mode 3840x2160 --pos 0x0 --rotate normal

sxhkd &
picom --experimental-backends &
nitrogen --restore &
redshift -P -O 3500 &
~/.config/polybar/launch.sh &
libinput-gestures-setup start &
/usr/bin/dunst &

bspc monitor DP-1 -d 1 2 3 4 5 6 7 8 A B
bspc monitor HDMI-3 -d 9 0
# bspc monitor DP-1 -s HDMI-3

gap=25
PANEL_HEIGHT=50
bspc config window_gap           $gap
bspc config left_padding        -$gap
bspc config right_padding       -$gap
# bspc config bottom_padding      0
bspc config bottom_padding      $(($PANEL_HEIGHT-$gap))
bspc config top_padding         -$gap

bspc config border_width         0
bspc config split_ratio          0.5

bspc config borderless_monocle   true
bspc config gapless_monocle      false

bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config single_monocle       true

bspc config pointer_modifier super
bspc config pointer_action1 move
bspc config pointer_action2 resize_corner
bspc config pointer_action3 resize_side

bspc config normal_border_color   \#000000
bspc config focused_border_color  \#683060
bspc config presel_feedback_color \#1e1125

bspc config swallow_first_click false
bspc config honor_size_hints    true

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true


