#! /bin/sh

sxhkd &
picom --experimental-backends &
nitrogen --restore &
redshift -P -O 4000 &
nm-applet &
~/.config/polybar/launch.sh &
libinput-gestures-setup start &

bspc monitor eDP-1 -d I II III IV V VI VII VIII IX X

bspc config border_width         1
bspc config window_gap          10
bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
